In [1]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
data=pd.Series([10,20,np.nan,40])
print(data)

0    10.0
1    20.0
2     NaN
3    40.0
dtype: float64

In [ ]:
data.isnull()     # True means the value is missing

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
data.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [7]:
data.isnull().sum()

np.int64(1)

In [ ]:
data.dropna()    #removingbnot available value

0    10.0
1    20.0
3    40.0
dtype: float64

In [11]:
# to fill the missing value

data.fillna(88)

0    10.0
1    20.0
2    88.0
3    40.0
dtype: float64

In [ ]:
data.fillna(data.mean())  #filling with mean

0    10.000000
1    20.000000
2    23.333333
3    40.000000
dtype: float64

In [17]:
df=pd.DataFrame({
    "Name":["Ann","Ben","John"],
    "Marks":[80,np.nan,90],
    "Age":[20,20,np.nan]
})

print(df)

   Name  Marks   Age
0   Ann   80.0  20.0
1   Ben    NaN  20.0
2  John   90.0   NaN

In [18]:
df.isnull()

    Name  Marks    Age
0  False  False  False
1  False   True  False
2  False  False   True

In [20]:
df.isnull().sum()

Name     0
Marks    1
Age      1
dtype: int64

In [21]:
df.dropna()

  Name  Marks   Age
0  Ann   80.0  20.0

In [ ]:
df.fillna(88)

   Name  Marks   Age
0   Ann   80.0  20.0
1   Ben   88.0  20.0
2  John   90.0  88.0

: