In [1]:
import pandas as pd
import numpy as np

In [2]:
marks=pd.Series([88,85,67,89,97])
print(marks)

0    88
1    85
2    67
3    89
4    97
dtype: int64

In [3]:
# Create an empty series
s=pd.Series
print(s)

<class 'pandas.Series'>

In [4]:
a=np.array([1,2,3,4,5])
s=pd.Series(a)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
# Creating series using Lists
l=[1,10,9.5,"Anu"]
s=pd.Series(l)
print(s)

0      1
1     10
2    9.5
3    Anu
dtype: object

In [6]:
# Create series using Dictionary
d={"Shirt":200,"Book":150,"Mobile":10000}
s=pd.Series(d)
print(s)

Shirt       200
Book        150
Mobile    10000
dtype: int64

In [7]:
# INDEXING
a=np.array([1,2,3,4,5])
s=pd.Series(a,index=["e","s2","sev","sim","anu"])
print(s)

e      1
s2     2
sev    3
sim    4
anu    5
dtype: int64

In [8]:
marks=pd.Series([85,72,90],index=["maths","python","statistic"])
print(marks)

maths        85
python       72
statistic    90
dtype: int64

In [9]:
l=[100,200,500,400]
p=pd.Series(l,index=["pen","shirt","book","mouse"])
print(p)

pen      100
shirt    200
book     500
mouse    400
dtype: int64

In [10]:
p.index

Index(['pen', 'shirt', 'book', 'mouse'], dtype='str')

In [11]:
p.array

<NumpyExtensionArray>
[100, 200, 500, 400]
Length: 4, dtype: int64

In [12]:
p.values

array([100, 200, 500, 400])

In [13]:
p.ndim

1

In [14]:
p.shape

(4,)

In [15]:
p.size

4

In [16]:
p.nbytes

32

In [17]:
p.memory_usage()

64

In [18]:
p.empty

False

online 30/09/26

In [19]:
# COMPUTAION ON ARRAY
a=np.array([10,20,30])
b=np.array([1,2,3])

In [20]:
a+b

array([11, 22, 33])

In [21]:
a-b

array([ 9, 18, 27])

In [22]:
a/b

array([10., 10., 10.])

In [23]:
a*b

array([10, 40, 90])

In [24]:
# SCALAR OPERATION
print(a*2)

[20 40 60]

In [25]:
print(a+5)

[15 25 35]

In [26]:
a=np.array([10,20,30,40,50])

In [27]:
np.sum(a)

np.int64(150)

In [28]:
np.mean(a)

np.float64(30.0)

In [29]:
np.std(a)

np.float64(14.142135623730951)

In [30]:
np.var(a)

np.float64(200.0)

In [31]:
np.min(a)

np.int64(10)

In [32]:
np.max(a)

np.int64(50)

In [33]:
# on axis
a=np.array([[10,20,30],[40,50,60]])

In [34]:
np.sum(a)

np.int64(210)

In [35]:
np.sum(a,axis=0)

array([50, 70, 90])

In [36]:
np.sum(a,axis=1)

array([ 60, 150])

In [37]:
#creating a dataframe
student={"Name":["Ann","Ben","John"],"Age":[20,30,40],"Place":["Kottayam","Alappuzha","Trivandrum"]}
df=pd.DataFrame(student)
print(df)

   Name  Age       Place
0   Ann   20    Kottayam
1   Ben   30   Alappuzha
2  John   40  Trivandrum

In [38]:
df1=pd.DataFrame(student,index=["s1","s2","s3"])
print(df1)

    Name  Age       Place
s1   Ann   20    Kottayam
s2   Ben   30   Alappuzha
s3  John   40  Trivandrum

In [39]:
data=[["Evik",20],["Ben",30],["Simon",35]]
df=pd.DataFrame(data,columns=["Name","Age"])
print(df)

    Name  Age
0   Evik   20
1    Ben   30
2  Simon   35

In [40]:
student={"Name":["Ann","Ben","John"],"Age":[20,30,40],"Place":["Kottayam","Alappuzha","Trivandrum"]}
df=pd.DataFrame(student)
print(df)

   Name  Age       Place
0   Ann   20    Kottayam
1   Ben   30   Alappuzha
2  John   40  Trivandrum

In [41]:
df.shape

(3, 3)

In [42]:
df.columns

Index(['Name', 'Age', 'Place'], dtype='str')

In [43]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [44]:
df.dtypes

Name       str
Age      int64
Place      str
dtype: object

In [45]:
df.size

9

In [46]:
# METHODS <+>

df.head(2)

  Name  Age      Place
0  Ann   20   Kottayam
1  Ben   30  Alappuzha

In [47]:
df.tail()

   Name  Age       Place
0   Ann   20    Kottayam
1   Ben   30   Alappuzha
2  John   40  Trivandrum

In [48]:
df.tail(1)

   Name  Age       Place
2  John   40  Trivandrum

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Place   3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [50]:
df.describe()

        Age
count   3.0
mean   30.0
std    10.0
min    20.0
25%    25.0
50%    30.0
75%    35.0
max    40.0

In [51]:
df["Name"].describe()

count       3
unique      3
top       Ann
freq        1
Name: Name, dtype: object

In [52]:
df["Age"].value_counts()

Age
20    1
30    1
40    1
Name: count, dtype: int64

In [53]:
marks=pd.Series([85,88,62,75],index=["Python","DBMS","Statistics","R"])
print(marks)

Python        85
DBMS          88
Statistics    62
R             75
dtype: int64

In [54]:
print(marks["Python"])

85

In [55]:
print(marks[["Python","R"]])

Python    85
R         75
dtype: int64

In [56]:
print(marks.iloc[0])

85

In [57]:
print(marks.iloc[[2,3]])    #put 2 "[]"s if for multiple value

Statistics    62
R             75
dtype: int64

In [58]:
print(marks.iloc[1:3])

DBMS          88
Statistics    62
dtype: int64

In [59]:
"""iloc = integer position based selection"""
"""loc = label based selection"""

'loc = label based selection'

In [60]:
print(marks.loc[["Python","R"]])

Python    85
R         75
dtype: int64

In [61]:
print(marks.loc["Python":"R"])

Python        85
DBMS          88
Statistics    62
R             75
dtype: int64

In [62]:
print(marks.loc["Python":"Statistics"])

Python        85
DBMS          88
Statistics    62
dtype: int64

In [63]:
student={"Name":["Ann","Ben","John"],"Age":[20,30,40],"Place":["Kottayam","Alappuzha","Trivandrum"]}
df=pd.DataFrame(student)
print(df)

   Name  Age       Place
0   Ann   20    Kottayam
1   Ben   30   Alappuzha
2  John   40  Trivandrum

In [64]:
print(df[["Name","Age"]])

   Name  Age
0   Ann   20
1   Ben   30
2  John   40

In [65]:
print(df["Name"])

0     Ann
1     Ben
2    John
Name: Name, dtype: str

In [66]:
print(df.iloc[0])

Name          Ann
Age            20
Place    Kottayam
Name: 0, dtype: object

In [67]:
#multiple rows

print(df.iloc[0:2])

  Name  Age      Place
0  Ann   20   Kottayam
1  Ben   30  Alappuzha

In [68]:
print(df.iloc[0:2,0:2])

  Name  Age
0  Ann   20
1  Ben   30

In [69]:
print(df.loc[[0,2]])

   Name  Age       Place
0   Ann   20    Kottayam
2  John   40  Trivandrum

In [70]:
print(df.loc[0:2])

   Name  Age       Place
0   Ann   20    Kottayam
1   Ben   30   Alappuzha
2  John   40  Trivandrum

In [71]:
print(df.loc[0:2,["Name","Age"]])

   Name  Age
0   Ann   20
1   Ben   30
2  John   40

BOOLIAN INDEXING

In [72]:
student={"Name":["Ann","Ben","John"],"Age":[20,30,40],"Marks":[40,50,75],"Place":["Kottayam","Alappuzha","Trivandrum"]}
df=pd.DataFrame(student, index=["s1","s2","s3"])
print(df)

    Name  Age  Marks       Place
s1   Ann   20     40    Kottayam
s2   Ben   30     50   Alappuzha
s3  John   40     75  Trivandrum

In [73]:
df[df["Age"]>35]

    Name  Age  Marks       Place
s3  John   40     75  Trivandrum

In [74]:
# multiple conditions
df[(df["Age"]>20)]

    Name  Age  Marks       Place
s2   Ben   30     50   Alappuzha
s3  John   40     75  Trivandrum

In [75]:
df[(df["Age"]>25) & (df["Marks"]>70)]

    Name  Age  Marks       Place
s3  John   40     75  Trivandrum

In [76]:
df[(df["Age"]>25) | (df["Marks"]>70)]

    Name  Age  Marks       Place
s2   Ben   30     50   Alappuzha
s3  John   40     75  Trivandrum

In [77]:
marks=pd.Series([80,70,90,60])

In [78]:
marks+5

0    85
1    75
2    95
3    65
dtype: int64

In [79]:
marks*5

0    400
1    350
2    450
3    300
dtype: int64

In [80]:
marks-5

0    75
1    65
2    85
3    55
dtype: int64

In [81]:
marks/5

0    16.0
1    14.0
2    18.0
3    12.0
dtype: float64

In [82]:
marks.sum()

np.int64(300)

In [83]:
marks.mean()

np.float64(75.0)

In [84]:
marks.min

<bound method Series.min of 0    80
1    70
2    90
3    60
dtype: int64>

In [85]:
marks.max()

np.int64(90)

In [86]:
marks.median()

np.float64(75.0)

In [87]:
marks.count()

np.int64(4)

In [88]:
marks.var

<bound method Series.var of 0    80
1    70
2    90
3    60
dtype: int64>

In [89]:
marks.std()

np.float64(12.909944487358056)

In [90]:
marks.var()

np.float64(166.66666666666666)

In [91]:
df.sort_values("Marks")

    Name  Age  Marks       Place
s1   Ann   20     40    Kottayam
s2   Ben   30     50   Alappuzha
s3  John   40     75  Trivandrum

In [92]:
df.sort_values("Marks",ascending=False)

    Name  Age  Marks       Place
s3  John   40     75  Trivandrum
s2   Ben   30     50   Alappuzha
s1   Ann   20     40    Kottayam

In [93]:
df.sort_index

<bound method DataFrame.sort_index of     Name  Age  Marks       Place
s1   Ann   20     40    Kottayam
s2   Ben   30     50   Alappuzha
s3  John   40     75  Trivandrum>

In [94]:
df.sort_index()

    Name  Age  Marks       Place
s1   Ann   20     40    Kottayam
s2   Ben   30     50   Alappuzha
s3  John   40     75  Trivandrum

In [95]:
df["Grade"]=["A+","A","B"]

In [96]:
df["Bonus"]=df["Marks"]+5

In [97]:
df

    Name  Age  Marks       Place Grade  Bonus
s1   Ann   20     40    Kottayam    A+     45
s2   Ben   30     50   Alappuzha     A     55
s3  John   40     75  Trivandrum     B     80

In [98]:
df.drop("Bonus",axis=1)

    Name  Age  Marks       Place Grade
s1   Ann   20     40    Kottayam    A+
s2   Ben   30     50   Alappuzha     A
s3  John   40     75  Trivandrum     B

In [99]:
df

    Name  Age  Marks       Place Grade  Bonus
s1   Ann   20     40    Kottayam    A+     45
s2   Ben   30     50   Alappuzha     A     55
s3  John   40     75  Trivandrum     B     80

In [100]:
df.drop("Bonus",axis=1,inplace=True)

In [101]:
df

    Name  Age  Marks       Place Grade
s1   Ann   20     40    Kottayam    A+
s2   Ben   30     50   Alappuzha     A
s3  John   40     75  Trivandrum     B

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

arr[0] = 11.5

print(arr)

In [2]:
l = [100, 200, 500, 400]

p = pd.Series(
l,
index=['pen', 'shirt', 'book', 'Mouse']
)

In [4]:
p.index

Index(['pen', 'shirt', 'book', 'Mouse'], dtype='str')

In [5]:
p.array

<NumpyExtensionArray>
[100, 200, 500, 400]
Length: 4, dtype: int64

In [6]:
p.values

array([100, 200, 500, 400])