In [1]:
import pandas as pd

In [4]:
date=pd.Timestamp("2026-10-14")
print(date)

2026-10-14 00:00:00

In [5]:
date=pd.Timestamp("2026-10-14 11:11:11")
print(date)

2026-10-14 11:11:11

In [9]:
dates=pd.to_datetime(["2026-10-14","2026-10-15","2026-10-16"])
print(dates)

DatetimeIndex(['2026-10-14', '2026-10-15', '2026-10-16'], dtype='datetime64[us]', freq=None)

In [12]:
# Creating a range of date

dates=pd.date_range(start="2026-10-14",end="2026-10-18")
print(dates)

DatetimeIndex(['2026-10-14', '2026-10-15', '2026-10-16', '2026-10-17',
               '2026-10-18'],
              dtype='datetime64[us]', freq='D')

In [13]:
# Date Range using periods

dates=pd.date_range(start="2026-10-14",periods=5)
print(dates)

DatetimeIndex(['2026-10-14', '2026-10-15', '2026-10-16', '2026-10-17',
               '2026-10-18'],
              dtype='datetime64[us]', freq='D')

In [19]:
date=pd.date_range(start="2026-10-14",periods=5,freq="ME")
print(date)

DatetimeIndex(['2026-10-31', '2026-11-30', '2026-12-31', '2027-01-31',
               '2027-02-28'],
              dtype='datetime64[us]', freq='ME')

In [20]:
date=pd.date_range(start="2026-10-14",periods=5,freq="D")
print(date)

DatetimeIndex(['2026-10-14', '2026-10-15', '2026-10-16', '2026-10-17',
               '2026-10-18'],
              dtype='datetime64[us]', freq='D')

In [21]:
date=pd.date_range(start="2026-01-01",periods=5,freq="h")
print(date)

DatetimeIndex(['2026-01-01 00:00:00', '2026-01-01 01:00:00',
               '2026-01-01 02:00:00', '2026-01-01 03:00:00',
               '2026-01-01 04:00:00'],
              dtype='datetime64[us]', freq='h')

In [22]:
date=pd.date_range(start="2026-01-01",periods=5)

sales=[100,120,150,130,180]

df=pd.DataFrame({"Sales":sales},index=dates)

print(df)

            Sales
2026-10-14    100
2026-10-15    120
2026-10-16    150
2026-10-17    130
2026-10-18    180

In [30]:
dates=df.loc["2026-01-03"]
print(date)
dates=df.loc["2026-01-02":"2026-01-02"]
print(dates)

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10'],
              dtype='datetime64[us]', freq='D')
            Sales
2026-01-02     20

In [27]:
date=pd.Timestamp("2026-09-30 10:30:00")

print(date.year)
print(date.month)
print(date.day)

2026
9
30

In [31]:
dates=pd.date_range(start="2026-01-01",periods=10,freq="D")

sales=[10,20,15,25,30,18,22,28,35,40]

df=pd.DataFrame({"Sales":sales},index=dates)


df.resample("ME".sum())

AttributeError: 'str' object has no attribute 'sum'

In [32]:
df["Sales"]=df["Sales"]*2
print(df)

            Sales
2026-01-01     20
2026-01-02     40
2026-01-03     30
2026-01-04     50
2026-01-05     60
2026-01-06     36
2026-01-07     44
2026-01-08     56
2026-01-09     70
2026-01-10     80

In [33]:
# Evaluate function

df=pd.DataFrame({"A":[10,20,30],"B":[2,4,6]})

df.eval("A+B")

0    12
1    24
2    36
dtype: int64

In [34]:
df.eval("C=A+B")

    A  B   C
0  10  2  12
1  20  4  24
2  30  6  36

In [ ]:
# Query

df=pd.DataFrame({
    "Name":["Anu","Meera","John","Rahul"],
    "Age":[20,22,19,25],
    "Marks":[85,91,72,88
]})

df.query("Marks>80")

    Name  Age  Marks
0    Anu   20     85
1  Meera   22     91
3  Rahul   25     88

In [36]:
# Query with multiple conditions

df.query("Age>20 and Marks>80")

    Name  Age  Marks
1  Meera   22     91
3  Rahul   25     88

In [37]:
df.query("Age>20 or Marks>80")

    Name  Age  Marks
0    Anu   20     85
1  Meera   22     91
3  Rahul   25     88

In [ ]:
# Comparing Query with Boolean Indexing

df[df["Marks"]>80]

df.query("Marks>80")

In [38]:
#  Query with variables

limit=80

df.query("Marks>@limit")

    Name  Age  Marks
0    Anu   20     85
1  Meera   22     91
3  Rahul   25     88

In [ ]:
Filters rows using a readable expression

Makes complex filtering conditions easier to write